### PR TITLE
Make EDD_Simple_Shipping Extensible

### PR DESCRIPTION
**Pull request by tannerm**
I am customizing the EDD checkout page and am rewriting the html for the different page components. I was able to hook into the other components and rewrite them, but I am not able to do that with the Simple Shipping. 

I tried extending EDD_Simple_Shipping to rewrite the address_fields() function, but was not able to access the helper functions it uses within the class since they are private. Can you update the EDD_Simple_Shipping to protected so that I can use them in my extended class?

### CODE REVIEW

**Comment by mindctrl** [comment]
Link for seeing it without whitespace changes: https://github.com/easydigitaldownloads/EDD-Simple-Shipping/pull/28/files?w=1

**Comment by tannerm** [comment]
Hey John! Is this something we are going to be able to merge in? If it will be included in the next version I'll go ahead and modify the clients plugin file now so I can close out the project.

**Comment by mindctrl** [comment]
@pippinsplugins thoughts here?

**Comment by pippinsplugins** [comment]
Looks good.

**Pull request merged**
